Add math.h header to Lightmaputil.cpp
treacherousfiend/LightmapUtil pull request #4
Opened 2022-06-14 17:50 UTC by HurricanePootis

I get this error without <math.h> being in headers, so I added it in this pull request.
```
[ 50%] Building CXX object CMakeFiles/lightmaputil.dir/src/LightmapUtil.cpp.o
/home/hurricane/LightmapUtil/src/LightmapUtil.cpp: In function ‘void checkSampleNeighbors(int, int, bool&, bool&)’:
/home/hurricane/LightmapUtil/src/LightmapUtil.cpp:444:73: error: ‘pow’ was not declared in this scope
  444 |                 float sample1R = dlightdataLDR[ lightmapSample1 ].r * ( pow( 2.0f, sample1E ) / 255 );
      |                                                                         ^~~
/home/hurricane/LightmapUtil/src/LightmapUtil.cpp:464:76: error: ‘pow’ was not declared in this scope
  464 |                 float HDRsample1R = dlightdataHDR[ lightmapSample1 ].r * ( pow( 2.0f, HDRsample1E ) / 255 );
      |                                                                            ^~~
make[2]: *** [CMakeFiles/lightmaputil.dir/build.make:76: CMakeFiles/lightmaputil.dir/src/LightmapUtil.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/lightmaputil.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

2022-06-14 21:25 UTC, getchoo requested changes
-1
does not use cpp standard libraries

more info: https://stackoverflow.com/questions/15656434/include-cmath-vs-include-math-h-in-a-c-program/15656459#15656459

2022-06-14 21:25 UTC, getchoo commented on src/LightmapUtil.cpp
> +#include <math.h>
`cmath` is best practice in cpp; `math.h` is a c header

2022-06-14 21:26 UTC, getchoo commented
fixes #7

2022-06-14 22:39 UTC, treacherousfiend commented
I have no clue how I was able to build without this.
 once you change it `#include <cmath>` i'll merge it

2022-06-16 00:02 UTC, treacherousfiend approved these changes

2022-06-16 00:02 UTC, merged